# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale      : "ko-KR"
title       : "IT전문가가 되고 싶은 담당자" # Meta 태그에 들어가는 영역 , masthead_title등이 없으면 기본값으로 나온다.
subtitle    : "Version 1.0" # 타이틀 아래에 나올 작은 글씨 
email       : kerogrammer@gmail.com
description : "주로 전산과 관련된 분야에 대한 생각을 적는 블로그" # Meta 태그에 들어가는 영역 
url         : "https://kerogrammer.github.io"
baseurl     : "" # the subpath of your site, e.g. /blog
repository  : "kerogrammer/kerogrammer.github.io" # GitHub username/repo-name  
teaser      : # "/assets/images/senior-couple-4723737_640.jpg" # 홈페이지 기본 티져 이미지
masthead_title      : "111111111111111" # 홈페이지 최 상탄에 들어갈 타이틀
breadcrumbs : true # 브래드크럼 사용 여부 true, false (default) , _data/ui-text.yml에 다국어 지원 가능합니다.
words_per_minute    : 200 # 해당 포스트 읽는데 걸리는 시간을 계산하기 위해 대락 분당 읽는 수가 몇글자가 될지 적는 공간.
twitter_username: kerogrammer
github_username:  kerogrammer

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
